apm-server:
  host: "0.0.0.0:8200"
  
  auth:
    anonymous:
      enabled: true
      allow_service: ['*']

# Configuración con credenciales de Elasticsearch
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "somethingsecret"

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "somethingsecret"

# CRÍTICO: Setup automático de templates y dashboards
setup.template.enabled: true
setup.template.overwrite: true
setup.dashboards.enabled: true
setup.dashboards.overwrite: true
setup.ilm.enabled: auto

# Configurar data streams manualmente para APM
setup.template.name: "apm"
setup.template.pattern: "apm-*"

# Logging
logging.level: info
logging.to_stderr: true
logging.to_files: false