#apm-server.yml
apm-server:
  host: "0.0.0.0:8200"
  
  # Configuración de autenticación
  auth:
    anonymous:
      enabled: true
      allow_service: ['express-metrics-api']  # ESPECÍFICO: Solo Express API
      allow_agent: ['*']
    
  # Configuración para OpenTelemetry
  otlp:
    grpc:
      enabled: true
      host: "0.0.0.0:8200"
    http:
      enabled: true  
      host: "0.0.0.0:8200"

# Configuración con credenciales de Elasticsearch
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "somethingsecret"
  
  # Configuración de índices ESPECÍFICOS para APM
  indices:
    - index: "apm-%{[agent.version]}-error-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "error"
    - index: "apm-%{[agent.version]}-transaction-%{+yyyy.MM.dd}" 
      when.contains:
        processor.event: "transaction"
    - index: "apm-%{[agent.version]}-span-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "span"
    - index: "apm-%{[agent.version]}-metric-%{+yyyy.MM.dd}"
      when.contains:
        processor.event: "metric"

  # FILTRO: Solo procesar datos de Express API
  pipeline: apm_user_agent
  pipelines:
    - pipeline: apm_user_agent
      processors:
        - drop:
            when.not.equals:
              service.name: "express-metrics-api"

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"  
  password: "somethingsecret"

# Setup automático de templates y dashboards
setup.template.enabled: true
setup.template.overwrite: true
setup.dashboards.enabled: true
setup.dashboards.overwrite: true
setup.ilm.enabled: auto

# Configurar templates específicos para Express API
setup.template.name: "apm-express"
setup.template.pattern: "apm-*"
setup.template.settings:
  index:
    number_of_shards: 1
    number_of_replicas: 0
    refresh_interval: "5s"

# Configuración específica para métricas
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    username: "elastic"
    password: "somethingsecret"

# Logging
logging.level: info
logging.to_stderr: true
logging.to_files: false
logging.selectors: ["*"]