#docker-compose-jenkis.yml
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    container_name: jenkins
    networks:
      - otel-network

volumes:
  jenkins_data:

networks:
  otel-network:
    external: true
    name: otel-network
